### ISSUE TITLE
Parallel requests not permitted

### ISSUE THREAD

**Issue by ferittuncer** [ferittuncer/ITU-Turkish-NLP-Pipeline-Caller#26]
I get this error message when I call 'pipelineNoisy`

> Parallel requests not permitted

I can confirm that this is not because of a caller change, as pipeline caller was working as expected before and no changes made by our side.

**Comment by ulgens** [comment]
The reason is API doesn't allow paralel requests as it says in the error message but it only happens in Travis, when there are multiple paralel builds. I changed "max concurrent build number" to 1 and it's okay now. We can close this issue.

**Comment by ferittuncer** [comment]
Actually I was getting this error in a manual call, not only in Travis. But if it's OK now, let's close.
